spring:
  datasource:
    username: bunkr_web
    password: fafRaV*4r6Ne
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/bunkr_web
  jooq:
      sql-dialect: postgres_9_5