/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq.tables;


import com.bunkrtech.website.persistence.jooq.Keys;
import com.bunkrtech.website.persistence.jooq.Public;
import com.bunkrtech.website.persistence.jooq.tables.records.AppParameterRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppParameter extends TableImpl<AppParameterRecord> {

    private static final long serialVersionUID = -2004275663;

    /**
     * The reference instance of <code>public.app_parameter</code>
     */
    public static final AppParameter APP_PARAMETER = new AppParameter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppParameterRecord> getRecordType() {
        return AppParameterRecord.class;
    }

    /**
     * The column <code>public.app_parameter.param_name</code>.
     */
    public final TableField<AppParameterRecord, String> PARAM_NAME = createField("param_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.app_parameter.param_value</code>.
     */
    public final TableField<AppParameterRecord, String> PARAM_VALUE = createField("param_value", org.jooq.impl.SQLDataType.VARCHAR.length(2500).nullable(false), this, "");

    /**
     * The column <code>public.app_parameter.created_at</code>.
     */
    public final TableField<AppParameterRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.app_parameter.updated_at</code>.
     */
    public final TableField<AppParameterRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.app_parameter</code> table reference
     */
    public AppParameter() {
        this("app_parameter", null);
    }

    /**
     * Create an aliased <code>public.app_parameter</code> table reference
     */
    public AppParameter(String alias) {
        this(alias, APP_PARAMETER);
    }

    private AppParameter(String alias, Table<AppParameterRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppParameter(String alias, Table<AppParameterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppParameterRecord> getPrimaryKey() {
        return Keys.APP_PARAMETER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppParameterRecord>> getKeys() {
        return Arrays.<UniqueKey<AppParameterRecord>>asList(Keys.APP_PARAMETER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameter as(String alias) {
        return new AppParameter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppParameter rename(String name) {
        return new AppParameter(name, null);
    }
}
