/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq.tables.records;


import com.bunkrtech.website.persistence.jooq.tables.AppParameter;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppParameterRecord extends UpdatableRecordImpl<AppParameterRecord> implements Record4<String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 358119160;

    /**
     * Setter for <code>public.app_parameter.param_name</code>.
     */
    public void setParamName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_parameter.param_name</code>.
     */
    public String getParamName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_parameter.param_value</code>.
     */
    public void setParamValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_parameter.param_value</code>.
     */
    public String getParamValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_parameter.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_parameter.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.app_parameter.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_parameter.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AppParameter.APP_PARAMETER.PARAM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AppParameter.APP_PARAMETER.PARAM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return AppParameter.APP_PARAMETER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AppParameter.APP_PARAMETER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getParamName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getParamValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameterRecord value1(String value) {
        setParamName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameterRecord value2(String value) {
        setParamValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameterRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameterRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppParameterRecord values(String value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppParameterRecord
     */
    public AppParameterRecord() {
        super(AppParameter.APP_PARAMETER);
    }

    /**
     * Create a detached, initialised AppParameterRecord
     */
    public AppParameterRecord(String paramName, String paramValue, Timestamp createdAt, Timestamp updatedAt) {
        super(AppParameter.APP_PARAMETER);

        set(0, paramName);
        set(1, paramValue);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
