/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq.tables.records;


import com.bunkrtech.website.persistence.jooq.tables.ContactInquiry;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactInquiryRecord extends UpdatableRecordImpl<ContactInquiryRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1381815570;

    /**
     * Setter for <code>public.contact_inquiry.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.contact_inquiry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.contact_inquiry.contact_name</code>.
     */
    public void setContactName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.contact_inquiry.contact_name</code>.
     */
    public String getContactName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contact_inquiry.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.contact_inquiry.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contact_inquiry.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.contact_inquiry.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.contact_inquiry.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.contact_inquiry.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ContactInquiry.CONTACT_INQUIRY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContactInquiry.CONTACT_INQUIRY.CONTACT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContactInquiry.CONTACT_INQUIRY.COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ContactInquiry.CONTACT_INQUIRY.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ContactInquiry.CONTACT_INQUIRY.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContactName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord value2(String value) {
        setContactName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord value3(String value) {
        setCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord value5(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactInquiryRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactInquiryRecord
     */
    public ContactInquiryRecord() {
        super(ContactInquiry.CONTACT_INQUIRY);
    }

    /**
     * Create a detached, initialised ContactInquiryRecord
     */
    public ContactInquiryRecord(Integer id, String contactName, String companyName, String email, String phone) {
        super(ContactInquiry.CONTACT_INQUIRY);

        set(0, id);
        set(1, contactName);
        set(2, companyName);
        set(3, email);
        set(4, phone);
    }
}
