/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq;


import com.bunkrtech.website.persistence.jooq.tables.AppParameter;
import com.bunkrtech.website.persistence.jooq.tables.ContactInquiry;
import com.bunkrtech.website.persistence.jooq.tables.ServicesOffered;
import com.bunkrtech.website.persistence.jooq.tables.records.AppParameterRecord;
import com.bunkrtech.website.persistence.jooq.tables.records.ContactInquiryRecord;
import com.bunkrtech.website.persistence.jooq.tables.records.ServicesOfferedRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ContactInquiryRecord, Integer> IDENTITY_CONTACT_INQUIRY = Identities0.IDENTITY_CONTACT_INQUIRY;
    public static final Identity<ServicesOfferedRecord, Integer> IDENTITY_SERVICES_OFFERED = Identities0.IDENTITY_SERVICES_OFFERED;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppParameterRecord> APP_PARAMETER_PKEY = UniqueKeys0.APP_PARAMETER_PKEY;
    public static final UniqueKey<ContactInquiryRecord> CONTACT_INQUIRY_PKEY = UniqueKeys0.CONTACT_INQUIRY_PKEY;
    public static final UniqueKey<ServicesOfferedRecord> SERVICES_OFFERED_PKEY = UniqueKeys0.SERVICES_OFFERED_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ContactInquiryRecord, Integer> IDENTITY_CONTACT_INQUIRY = createIdentity(ContactInquiry.CONTACT_INQUIRY, ContactInquiry.CONTACT_INQUIRY.ID);
        public static Identity<ServicesOfferedRecord, Integer> IDENTITY_SERVICES_OFFERED = createIdentity(ServicesOffered.SERVICES_OFFERED, ServicesOffered.SERVICES_OFFERED.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AppParameterRecord> APP_PARAMETER_PKEY = createUniqueKey(AppParameter.APP_PARAMETER, "app_parameter_pkey", AppParameter.APP_PARAMETER.PARAM_NAME);
        public static final UniqueKey<ContactInquiryRecord> CONTACT_INQUIRY_PKEY = createUniqueKey(ContactInquiry.CONTACT_INQUIRY, "contact_inquiry_pkey", ContactInquiry.CONTACT_INQUIRY.ID);
        public static final UniqueKey<ServicesOfferedRecord> SERVICES_OFFERED_PKEY = createUniqueKey(ServicesOffered.SERVICES_OFFERED, "services_offered_pkey", ServicesOffered.SERVICES_OFFERED.ID);
    }
}
