/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq;


import com.bunkrtech.website.persistence.jooq.tables.AppParameter;
import com.bunkrtech.website.persistence.jooq.tables.ContactInquiry;
import com.bunkrtech.website.persistence.jooq.tables.ServicesOffered;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -57578020;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_parameter</code>.
     */
    public final AppParameter APP_PARAMETER = com.bunkrtech.website.persistence.jooq.tables.AppParameter.APP_PARAMETER;

    /**
     * The table <code>public.contact_inquiry</code>.
     */
    public final ContactInquiry CONTACT_INQUIRY = com.bunkrtech.website.persistence.jooq.tables.ContactInquiry.CONTACT_INQUIRY;

    /**
     * The table <code>public.services_offered</code>.
     */
    public final ServicesOffered SERVICES_OFFERED = com.bunkrtech.website.persistence.jooq.tables.ServicesOffered.SERVICES_OFFERED;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CONTACT_INQUIRY_ID_SEQ,
            Sequences.SERVICES_OFFERED_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AppParameter.APP_PARAMETER,
            ContactInquiry.CONTACT_INQUIRY,
            ServicesOffered.SERVICES_OFFERED);
    }
}
