/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.contact_inquiry_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_INQUIRY_ID_SEQ = new SequenceImpl<Long>("contact_inquiry_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.services_offered_id_seq</code>
     */
    public static final Sequence<Long> SERVICES_OFFERED_ID_SEQ = new SequenceImpl<Long>("services_offered_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
