/*
 * This file is generated by jOOQ.
*/
package com.bunkrtech.website.persistence.jooq;


import com.bunkrtech.website.persistence.jooq.tables.AppParameter;
import com.bunkrtech.website.persistence.jooq.tables.ContactInquiry;
import com.bunkrtech.website.persistence.jooq.tables.ServicesOffered;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_parameter</code>.
     */
    public static final AppParameter APP_PARAMETER = com.bunkrtech.website.persistence.jooq.tables.AppParameter.APP_PARAMETER;

    /**
     * The table <code>public.contact_inquiry</code>.
     */
    public static final ContactInquiry CONTACT_INQUIRY = com.bunkrtech.website.persistence.jooq.tables.ContactInquiry.CONTACT_INQUIRY;

    /**
     * The table <code>public.services_offered</code>.
     */
    public static final ServicesOffered SERVICES_OFFERED = com.bunkrtech.website.persistence.jooq.tables.ServicesOffered.SERVICES_OFFERED;
}
